In [1]:
!pip install requests pandas sqlalchemy pymysql

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.1.31)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.7 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [2]:
!pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 25.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10

In [3]:
import requests
import pandas as pd
from sqlalchemy import create_engine

In [4]:
url = 'https://api.tvmaze.com/shows?page=1'

In [5]:
response = requests.get(url)
shows_data = response.json()

In [6]:
df_shows = pd.json_normalize(shows_data)

In [7]:
df_shows = df_shows[['id', 'name', 'language', 'genres', 'premiered', 'rating.average', 'network.name']]

In [8]:
df_shows.columns = ['Show_ID', 'Show_Name', 'Language', 'Genres', 'Premiered', 'Rating', 'Network']

In [9]:
df = pd.DataFrame(df_shows)
df

,Show_ID,Show_Name,Language,Genres,Premiered,Rating,Network
0,250,Kirby Buckets,English,[Comedy],2014-10-20,NaN,Disney XD
1,251,Downton Abbey,English,"[Drama, Family, Romance]",2010-09-26,8.8,ITV1
2,252,Girl Meets World,English,"[Drama, Comedy, Family]",2014-06-27,7.7,Disney Channel
3,253,Hell's Kitchen,English,[Food],2005-05-30,6.9,FOX
4,254,World Series of Poker,English,[Sports],2006-08-22,7.8,NaN
...,...,...,...,...,...,...,...
240,495,Naruto,Japanese,"[Action, Adventure, Anime, Fantasy]",2002-10-03,8.1,TV Tokyo
241,496,100 Things to Do Before High School,English,"[Comedy, Children]",2014-11-11,6.5,Nickelodeon
242,497,Strip the Cosmos,English,"[Mystery, Nature, History]",2014-11-12,7.2,Science
243,498,Dogs of War,English,[War],2014-11-11,NaN,A&E
244,499,Married... with Children,English,"[Comedy, Family, Adult]",1987-04-05,8.1,FOX

In [25]:
user = 'postgres'
password = 'isba_4715'
host = 'isba-dev-02.ctwgc6gcobls.us-east-2.rds.amazonaws.com'
port = '5432'
database = 'sql_project'

In [26]:
engine = create_engine(f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}')

In [27]:
df_shows['Genres'] = df_shows['Genres'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

In [28]:
df_shows.to_sql(
    name='tvmaze_shows',
    con=engine,
    if_exists='replace',
    index=False
)

245